version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
      - cache
    environment:
      - PORT=3000
      - DATABASE_URL=postgres://postgres:password123@db:5432/lautanuang
      - REDIS_URL=redis://cache:6379
      - JWT_SECRET=${JWT_SECRET}

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: lautanuang
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      # Menyisipkan skrip seed saat inisialisasi awal
      - ./database/seed.sql:/docker-entrypoint-initdb.d/seed.sql

  cache:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  pgdata: